import { Providers } from "@components/providers";
import "@styles/styles.css";
import { cn } from "@utils/cn";
import { fontSans } from "@utils/fonts";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>): Promise<JSX.Element> {
  return (
    <html lang="en" suppressHydrationWarning={true}>
      <head />
      <body
        className={cn(
          "min-h-screen bg-background font-sans antialiased relative",
          fontSans.variable,
        )}
      >
        <Providers>
          <div className="FTSContainer z-10 flex min-h-screen flex-col">
            <main className="min-h-[var(--section-height)] flex-1">
              {children}
            </main>
          </div>
        </Providers>
      </body>
    </html>
  );
}
