version: "3.8"

networks:
  tinacms_default: # More descriptive network name

services:
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    expose:
      - 27017
    networks:
      - tinacms_default

  tinacms:
  depends_on:
      - mongo
    build: .
    ports:
      - "3000:3000"
    expose:
      - 3000
    networks:
      - tinacms_default
    volumes:
      - .env:/app/.env  # Assuming you have a .env file outside the compose file
    environment:
      MONGODB_URI: mongodb://mongo:27017/_mdb_catalog  # Using the defined service name
    
