version: "3.8"

services:
  app:
    network_mode: host
    build:
      network: host
      context: .
    image: fts-tinacms:latest
    expose:
      - 3000
    volumes:
      - ../.env:/app/.env # Assuming you have a .env file outside the compose file
