version: "3.8"

services:
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    expose: 
      - 27017
    networks:
      - tina
    volumes:
      - db:/data/db
    environment: 
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=12345678

  app:
    build: .
    ports:
      - "3000:3000" 
    volumes:
      - .env:/app/.env
    networks:
      - tina
volumes:
  db:


networks:
  tina:
    driver: bridge
