version: "3.8"

services:
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    networks:
      - tina
    volumes:
      - db:/data/db

  app:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .env:/app/.env

volumes:
  db:


networks:
  tina:
    driver: bridge
