version: "3.8"

services:
  tinacms:
    build: .  # Specifies the current directory as the build context
    ports:
      - "3000:3000"  # Map container port 3000 to host port 3000
    volumes:
      - .env:/app/.env  # Mount .env file from host directory to container's /app/.env
    environment:  # Add the environment section for tinacms service
      MONGODB_URI: mongodb://mongo:27017/tinacms  # Set the MONGODB_URI variable

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"  # Map container port 27017 to host port 27017
    volumes:
      - mongo-data:/data/db  # Mount volume for persistent data (optional)

# New section: define the mongo-data volume
volumes:
  mongo-data:  # Create a named volume for Mongo data
