version: "3.8"

services:
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    expose: 
      - 27017
    networks:
      - tinacms_tina
    volumes:
      - db:/data/db
    environment: 
   uri: "mongodb://admin:12345678@172.18.0.2:27017/

  app:
    build: .
    ports:
      - "3000:3000" 
    volumes:
      - .env:/app/.env
    networks:
      - tinacms_tina
volumes:
  db:


networks:
  tinacms_tina:
    driver: bridge
    name: tinacms_tina
