import type { Metadata } from "next";
import { cn } from "@/lib/utils";
import { fontSans } from "@/lib/fonts";
import "../globals.css";
import { ThemeProvider } from "@/components/theme-provider";
import client from "@/tina/__generated__/client";
import Header from "@/components/header";
import Footer from "@/components/footer";
import { GlobalQuery } from "@/tina/__generated__/types";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const connection = await client.queries.globalConnection();

  return (
    <html lang="en">
      <head />
      <body
        className={cn(
          "min-h-screen bg-background font-sans antialiased",
          fontSans.variable
        )}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <div className="flex min-h-screen flex-col container">
            <Header {...connection} className="py-8 flex-none" />

            <main className="flex-1">{children}</main>
            <Footer {...connection} className="py-8 flex-none" />
          </div>
        </ThemeProvider>
      </body>
    </html>
  );
}
